apply plugin: 'com.android.library'

android {
    namespace "com.appsflyer.unitywrapper"
    compileSdkVersion 34

    defaultConfig {
        minSdkVersion 16
        targetSdkVersion 34

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        consumerProguardFiles 'consumer-rules.pro'
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

}

repositories {
    mavenCentral()
    flatDir { dirs 'libs' }
}


dependencies {
    compileOnly fileTree(dir: 'libs', include: ['*.jar'])
    compileOnly(name: 'af-android-plugin-bridge', ext: 'aar')
    compileOnly(name: 'af-android-sdk-base', ext: 'aar')
    compileOnly 'androidx.appcompat:appcompat:1.1.0'
    compileOnly(name: 'af-android-sdk-dev', ext: 'aar')
    compileOnly "com.appsflyer:purchase-connector:$ANDROID_PC_VERSION"
    compileOnly 'com.android.billingclient:billing:5.2.0'
}

apply from: file('publish.gradle')
