name: checksum

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: test emv
        shell: bash
        run: |
          echo "action path $GITHUB_ACTION_PATH"
     
