name: checksum

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v2.3.4
        
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.7.8'
      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install unitypackage_extractor
      - name: execute py script
        run:
          python .github/workflows/scripts/extractPacakge.py
     
