name: check packages

on:
  push:
    tags:        
      - '*'           

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v2.3.4
        
      - name: Name of the branch
        run: | 
          VERSION = $(echo "${{GITHUB_REF_NAME}}")
          echo "PLUGIN_VERSION=$VERSION" >> $GITHUB_ENV
        
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.7.8'
      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install unitypackage_extractor
      - name: execute py script
        run:
          python .github/workflows/scripts/extractPackage.py appsflyer-unity-plugin-${{env.PLUGIN_VERSION}}.unitypackage strict-mode-sdk/appsflyer-unity-plugin-strict-mode-${{env.PLUGIN_VERSION}}.unitypackage
     
