name: Release plugin to QA

on:
  push:
    branches:
      - releases/[0-9].x.x/[0-9].[0-9].x/[0-9].[0-9].[0-9]
    paths-ignore:
      - '**.md'
      - '**.yml'

jobs:
   Deploy-To-QA:
    uses: ./.github/workflows/deploy-to-QA.yml
