name: plugin release to Production

on:
  workflow_call:
    inputs:
      plugin_version:
        required: true
        type: string
      branch_name:
        required: true
        type: string

jobs:
  Release-To-Production:
    runs-on: ubuntu-latest
    environment: Production
    steps:
      - uses: actions/checkout@v4

      - name: Configure git
        env:
          COMMIT_AUTHOR: ${{ secrets.CI_USERNAME }}
          COMMIT_EMAIL: ${{ secrets.CI_EMAIL }}
        run: |
          git config --global user.name "$COMMIT_AUTHOR"
          git config --global user.email "$COMMIT_EMAIL"

      - name: Create GitHub Release
        env:
          VTAG: v${{ inputs.plugin_version }}
          TAG: ${{ inputs.plugin_version }}
        uses: actions/github-script@v7
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          script: |
            try {
              await github.rest.repos.createRelease({
                draft: false,
                generate_release_notes: false,
                name: process.env.VTAG,
                owner: context.repo.owner,
                prerelease: false,
                repo: context.repo.repo,
                tag_name: process.env.TAG
              });
            } catch (error) {
              core.setFailed(error.message);
            }
