name: check headers
on:
  push:
    branches:
      - main

jobs:
  conditional_job_check_files:
    runs-on: 'ubuntu-20.04'
    outputs:
      docs_changed: ${{ steps.check_file_changed.outputs.docs_changed }}
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 5
    - shell: pwsh
      id: check_file_changed
      run: |
        # Diff HEAD with the previous commit
        $diff = git diff --name-only HEAD^ HEAD

        $SourceDiff = $diff | Where-Object {$_ -match '.sh$' }
        $HasDiff = $SourceDiff.Length -gt 0

        Write-Host "::set-output name=docs_changed::$HasDiff"

  # Run the job only with "docs_changed" equals "True"
  conditional_job:
    runs-on: 'ubuntu-20.04'
    needs: [ conditional_job_check_files ]
    if: needs.conditional_job_check_files.outputs.docs_changed == 'True'
    steps:
    - shell: pwsh
      run: echo check files
